=== wilfred12/langlv-wp/trunk/home-projects/TIBCO/iso8583-adapter/02.source/schemas/isomsg.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns="http://langlv.homeproject.org/iso8583adapter/schemas"
	 targetNamespace="http://langlv.homeproject.org/iso8583adapter/schemas"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="isomsg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="mti" type="xs:string"/>
			<xs:attribute name="pcode" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:string"/>
					<xs:attribute name="value" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== wilfred12/langlv-wp/home-projects/TIBCO/iso8583-adapter/02.source/schemas/example_msg_request.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<isomsg mti = "0100" pcode = "300000" xmlns = "http://langlv.homeproject.org/iso8583adapter/schemas" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://langlv.homeproject.org/iso8583adapter/schemas isomsg.xsd"> 
	<field id = "0" value = "0100"/> 
	<field id = "3" value = "300000"/> 
	<field id = "4" value = "000000043170"/> 
	<field id = "11" value = "000236"/> 
	<field id = "12" value = "124927"/> 
	<field id = "13" value = "0605"/> 
	<field id = "22" value = "022"/> 
	<field id = "24" value = "003"/> 
	<field id = "25" value = "00"/> 
	<field id = "35" value = "123456789012345=0508123456789"/> 
	<field id = "41" value = "29110001"/> 
	<field id = "42" value = "000000000100001"/> 
	<field id = "49" value = "840"/> 
	<field id = "62" value = "062881"/>
</isomsg>
